dist: xenial
sudo: required
language: java
jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - develop
    - /support\/.*/

stages:
  - test

install: travis_retry mvn install -DskipTests=true -B -V

jobs:
  include:
    - stage: test
      name: "Build and test"
      before_script: cd ${TRAVIS_BUILD_DIR}/surf
      script: travis_retry mvn test
    - name: "WhiteSource scan"
      # only on SP branches or master and if it is not a PR
      if: fork = false AND (branch = develop OR branch =~ /support\/SP\/.*/) AND type != pull_request
      script:
        # Download the latest version of WhiteSource Unified Agent
        - curl -LJO https://github.com/whitesource/unified-agent-distribution/raw/master/standAlone/wss-unified-agent.jar
        # Run WhiteSource Unified Agent
        - java -jar wss-unified-agent.jar -apiKey ${WHITESOURCE_API_KEY} -c .wss-unified-agent.config